## 1. 环境配置

In [1]:
import pandas as pd
from plotnine import *
from plotnine.data import mpg



dataPath = "/mnt/disk2/dataset/kaggle/framingham.csv"

## 2. 数据导入：Framingham数据

| 列名                  | 含义                   | 数据类型    | 缺失率 |
| ------------------- | -------------------- | ------- | --- |
| **male**            | 性别（1=男, 0=女）         | 二分类     | 0%  |
| **age**             | 年龄（岁）                | 连续      | 0%  |
| **education**       | 教育水平（1~4）            | 有序分类    | 约2% |
| **currentSmoker**   | 当前是否吸烟（1/0）          | 二分类     | 0%  |
| **cigsPerDay**      | 每日吸烟量（支/天）           | 连续      | 约1% |
| **BPMeds**          | 是否服用降压药（1/0）         | 二分类     | 约1% |
| **prevalentStroke** | 基线是否有卒中史（1/0）        | 二分类     | 0%  |
| **prevalentHyp**    | **基线是否已有高血压**（1/0）   | 二分类     | 0%  |
| **diabetes**        | 是否有糖尿病（1/0）          | 二分类     | 0%  |
| **totChol**         | 总胆固醇（mg/dL）          | 连续      | 约1% |
| **sysBP**           | 收缩压（mmHg）            | 连续      | 0%  |
| **diaBP**           | 舒张压（mmHg）            | 连续      | 0%  |
| **BMI**             | 体重指数（kg/m²）          | 连续      | 约1% |
| **heartRate**       | 心率（次/分）              | 连续      | 0%  |
| **glucose**         | 血糖（mg/dL）            | 连续      | 约3% |
| **TenYearCHD**      | **10年内是否发生冠心病**（1/0） | 二分类（结局） | 0%  |

In [2]:
df = pd.read_csv(dataPath)
df

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4235,0,48,2.0,1,20.0,NaN,0,0,0,248.0,131.0,72.0,22.00,84.0,86.0,0
4236,0,44,1.0,1,15.0,0.0,0,0,0,210.0,126.5,87.0,19.16,86.0,NaN,0
4237,0,52,2.0,0,0.0,0.0,0,0,0,269.0,133.5,83.0,21.47,80.0,107.0,0
4238,1,40,3.0,0,0.0,0.0,0,1,0,185.0,141.0,98.0,25.60,67.0,72.0,0
4239,0,39,3.0,1,30.0,0.0,0,0,0,196.0,133.0,86.0,20.91,85.0,80.0,0

## 3. 描述性统计

In [9]:
# 10年发病率
print(f"结局变量分布:\n{df['TenYearCHD'].value_counts(normalize=True)}")

结局变量分布:
TenYearCHD
0    0.848113
1    0.151887
Name: proportion, dtype: float64

In [10]:
age_by_outcome = df.groupby('TenYearCHD')
age_by_outcome.groups

{0: [0, 1, 2, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 16, 18, 19, 20, 21, 22, 23, 24, 26, 27, 29, 30, 31, 34, 35, 36, 37, 38, 39, 40, 41, 43, 45, 46, 47, 49, 51, 52, 53, 54, 55, 56, 57, 58, 60, 61, 62, 63, 65, 66, 67, 68, 69, 70, 71, 72, 73, 76, 77, 78, 79, 80, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 95, 96, 98, 99, 100, 101, 102, 103, 104, 105, 106, 109, 110, 111, 112, 113, 114, 117, 118, 119, 120, 121, 122, ...], 1: [3, 6, 15, 17, 25, 28, 32, 33, 42, 44, 48, 50, 59, 64, 74, 75, 81, 94, 97, 107, 108, 115, 116, 137, 138, 139, 140, 143, 145, 148, 152, 153, 168, 170, 176, 187, 190, 191, 193, 194, 196, 205, 208, 226, 227, 230, 234, 238, 241, 246, 247, 259, 266, 270, 277, 280, 284, 294, 305, 311, 325, 328, 336, 340, 343, 344, 359, 360, 363, 367, 369, 371, 375, 376, 391, 394, 395, 398, 425, 448, 471, 481, 482, 485, 494, 500, 512, 520, 522, 523, 524, 533, 541, 543, 551, 553, 558, 566, 573, 576, ...]}

In [11]:
df.describe()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
count,4240.000000,4240.000000,4135.000000,4240.000000,4211.000000,4187.000000,4240.000000,4240.000000,4240.000000,4190.000000,4240.000000,4240.000000,4221.000000,4239.000000,3852.000000,4240.000000
mean,0.429245,49.580189,1.979444,0.494104,9.005937,0.029615,0.005896,0.310613,0.025708,236.699523,132.354599,82.897759,25.800801,75.878981,81.963655,0.151887
std,0.495027,8.572942,1.019791,0.500024,11.922462,0.169544,0.076569,0.462799,0.158280,44.591284,22.033300,11.910394,4.079840,12.025348,23.954335,0.358953
min,0.000000,32.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,107.000000,83.500000,48.000000,15.540000,44.000000,40.000000,0.000000
25%,0.000000,42.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,206.000000,117.000000,75.000000,23.070000,68.000000,71.000000,0.000000
50%,0.000000,49.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,234.000000,128.000000,82.000000,25.400000,75.000000,78.000000,0.000000
75%,1.000000,56.000000,3.000000,1.000000,20.000000,0.000000,0.000000,1.000000,0.000000,263.000000,144.000000,90.000000,28.040000,83.000000,87.000000,0.000000
max,1.000000,70.000000,4.000000,1.000000,70.000000,1.000000,1.000000,1.000000,1.000000,696.000000,295.000000,142.500000,56.800000,143.000000,394.000000,1.000000

## 4. 数据清洗

In [ ]:

def rmPreStroke(df: pd.DataFrame)->pd.DataFrame:
    return df[df['prevalentStroke']==0]

cleanDf = rmPreStroke(df=df).dropna()
cleanDf

## 5. Logistic回归

### 划分训练集和测试集

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

为所有用于预测的自变量分配一个影响系数

In [15]:
x = cleanDf.drop(columns=['TenYearCHD'])
y = cleanDf['TenYearCHD']

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=42, stratify=y)

In [17]:
model = LogisticRegression(max_iter=100)
model.fit(x_train,y_train)

/mnt/disk1/project/MedCross/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression

LogisticRegression()

In [19]:
import numpy as np
coef_df = pd.DataFrame({
    "Feature": x.columns,
    "Coefficient": model.coef_[0],
    "Odds Ratio": np.exp(model.coef_[0])
}).sort_values("Coefficient", key=abs, ascending=False)
print(f"Intercept: {model.intercept_[0]:.4f}")
print(f"Accuracy: {model.score(x_test, y_test):.4f}")
coef_df

Intercept: -0.4411
Accuracy: 0.8544

            Feature  Coefficient  Odds Ratio
7      prevalentHyp     0.960017    2.611742
0              male     0.532380    1.702981
5            BPMeds     0.189076    1.208133
2         education    -0.177812    0.837100
8          diabetes     0.169517    1.184732
3     currentSmoker    -0.127341    0.880433
12              BMI    -0.065647    0.936461
1               age     0.037296    1.038000
11            diaBP    -0.030572    0.969891
13        heartRate    -0.016271    0.983861
4        cigsPerDay     0.014429    1.014534
10            sysBP     0.013958    1.014056
14          glucose     0.004935    1.004947
9           totChol    -0.001502    0.998499
6   prevalentStroke     0.000000    1.000000