In [2]:
import os

from pyiceberg.catalog import load_catalog
from pyiceberg.schema import Schema
from pyiceberg.types import LongType, StringType, DoubleType

catalog = load_catalog(
    "default",
    **{
        "type": "rest",
        "uri": os.environ["ICEBERG_REST_URI"],
        "s3.endpoint": os.environ["ICEBERG_S3_ENDPOINT_PUBLIC"],
        "s3.access-key-id": os.environ["ICEBERG_S3_ACCESS_KEY_ID"],
        "s3.secret-access-key": os.environ["ICEBERG_S3_SECRET_ACCESS_KEY"],
    },
)

In [3]:
catalog.list_tables('ukb')

[('ukb', 'hypertension_cohort'), ('ukb', 'olink_instance_0')]

In [5]:
hypertension_cohort = catalog.load_table("ukb.hypertension_cohort")
olink_cohort = catalog.load_table("ukb.olink_instance_0")

In [11]:
import os
os.environ["AWS_ACCESS_KEY_ID"] = os.environ["ICEBERG_S3_ACCESS_KEY_ID"]
os.environ["AWS_SECRET_ACCESS_KEY"] = os.environ["ICEBERG_S3_SECRET_ACCESS_KEY"]
os.environ["AWS_ENDPOINT_URL"] = os.environ["ICEBERG_S3_ENDPOINT_PUBLIC"]
os.environ["AWS_REGION"] = os.environ["ICEBERG_S3_REGION"]
os.environ["AWS_ALLOW_HTTP"] = "true"

import polars as pl

In [14]:
hp_df = pl.scan_iceberg(hypertension_cohort)
olink_df = pl.scan_iceberg(olink_cohort)

In [13]:
hp_df.count().collect()

shape: (1, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ participa ┆ participa ┆ participa ┆ participa ┆ … ┆ participa ┆ participa ┆ participa ┆ olink_in │
│ nt.eid    ┆ nt.p13128 ┆ nt.p31    ┆ nt.p21003 ┆   ┆ nt.p4079_ ┆ nt.p2966_ ┆ nt.p20161 ┆ stance_0 │
│ ---       ┆ 6         ┆ ---       ┆ _i0       ┆   ┆ i0_a1     ┆ i0        ┆ _i0       ┆ .eid     │
│ u32       ┆ ---       ┆ u32       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ u32       ┆           ┆ u32       ┆   ┆ u32       ┆ u32       ┆ u32       ┆ u32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 501936    ┆ 209310    ┆ 501936    ┆ 501936    ┆ … ┆ 460763    ┆ 134546    ┆ 150773    ┆ 52995    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [15]:
olink_df.count().collect()

shape: (1, 2_924)
┌───────┬───────┬───────┬────────┬───┬───────┬───────┬───────┬───────┐
│ eid   ┆ a1bg  ┆ aamdc ┆ aarsd1 ┆ … ┆ znrf4 ┆ zp3   ┆ zp4   ┆ zpr1  │
│ ---   ┆ ---   ┆ ---   ┆ ---    ┆   ┆ ---   ┆ ---   ┆ ---   ┆ ---   │
│ u32   ┆ u32   ┆ u32   ┆ u32    ┆   ┆ u32   ┆ u32   ┆ u32   ┆ u32   │
╞═══════╪═══════╪═══════╪════════╪═══╪═══════╪═══════╪═══════╪═══════╡
│ 52995 ┆ 44833 ┆ 43574 ┆ 51259  ┆ … ┆ 44555 ┆ 43574 ┆ 43164 ┆ 43322 │
└───────┴───────┴───────┴────────┴───┴───────┴───────┴───────┴───────┘