In [1]:
from dx_client import DXClient, DXClientConfig


from typing import List
import numpy as np

import dotenv
dotenv.load_dotenv('../../.env')

True

In [2]:
config = DXClientConfig(
    
)
client =DXClient(config=config)
client.connect()

In [3]:
dd = client.get_data_dictionary()

In [4]:
# 1. search hypertension related fields


# 在 title、folder_path、description 中搜索
htn = dd[
    dd['title'].str.lower().str.contains('hypertension|blood pressure|systolic|diastolic', na=False) |
    dd['folder_path'].str.lower().str.contains('hypertension|blood.pressure', na=False)
]

htn
# htn[['entity', 'name', 'title', 'type', 'folder_path', 'coding_name']].to_string()

,entity,name,type,primary_key_type,coding_name,concept,description,folder_path,is_multi_select,is_sparse_coding,linkout,longitudinal_axis_type,referenced_entity_field,relationship,title,units
32,participant,p36_i0,string,NaN,NaN,NaN,NaN,Assessment centre > Physical measures > Blood ...,NaN,NaN,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,NaN,NaN,NaN,Blood pressure device ID | Instance 0,NaN
33,participant,p36_i1,string,NaN,NaN,NaN,NaN,Assessment centre > Physical measures > Blood ...,NaN,NaN,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,NaN,NaN,NaN,Blood pressure device ID | Instance 1,NaN
34,participant,p36_i2,string,NaN,NaN,NaN,NaN,Assessment centre > Physical measures > Blood ...,NaN,NaN,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,NaN,NaN,NaN,Blood pressure device ID | Instance 2,NaN
35,participant,p36_i3,string,NaN,NaN,NaN,NaN,Assessment centre > Physical measures > Blood ...,NaN,NaN,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,NaN,NaN,NaN,Blood pressure device ID | Instance 3,NaN
36,participant,p37_i0,string,NaN,NaN,NaN,NaN,Assessment centre > Physical measures > Blood ...,NaN,NaN,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,NaN,NaN,NaN,Blood pressure manual sphygmomanometer device ...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32221,participant,p132187,integer,NaN,data_coding_2171,NaN,NaN,Health-related outcomes > First occurrences > ...,NaN,NaN,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,NaN,NaN,NaN,Source of report of O13 (gestational [pregnanc...,NaN
32222,participant,p132188,date,NaN,data_coding_819,NaN,NaN,Health-related outcomes > First occurrences > ...,NaN,yes,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,NaN,NaN,NaN,Date O14 first reported (gestational [pregnanc...,NaN
32223,participant,p132189,integer,NaN,data_coding_2171,NaN,NaN,Health-related outcomes > First occurrences > ...,NaN,NaN,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,NaN,NaN,NaN,Source of report of O14 (gestational [pregnanc...,NaN
32226,participant,p132192,date,NaN,data_coding_819,NaN,NaN,Health-related outcomes > First occurrences > ...,NaN,yes,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,NaN,NaN,NaN,Date O16 first reported (unspecified maternal ...,NaN
32227,participant,p132193,integer,NaN,data_coding_2171,NaN,NaN,Health-related outcomes > First occurrences > ...,NaN,NaN,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,NaN,NaN,NaN,Source of report of O16 (unspecified maternal ...,NaN

In [5]:
proteome = dd[dd['entity'].str.contains(r'olink_*')]
proteome_fields = proteome['entity'] + '.' + proteome['name']

proteome_fields

32803       olink_instance_0.eid
32804      olink_instance_0.a1bg
32805     olink_instance_0.aamdc
32806    olink_instance_0.aarsd1
32807     olink_instance_0.abca2
                  ...
38650     olink_instance_3.xrcc4
38651      olink_instance_3.yes1
38652    olink_instance_3.ythdf3
38653    olink_instance_3.zbtb16
38654    olink_instance_3.zbtb17
Length: 5852, dtype: str

In [6]:
# cohort = client.create_cohort(name='auto_cohort', entity_fields=['olink_instance_0$A1BG', 'participant$p132601'], filters = {
#     "logic": "and",
#     "pheno_filters": {
#         "logic": "and",
#         "compound": [
#             {
#                 "name": "phenotype",
#                 "logic": "and",
#                 "filters": {
#                     # 字段名 → 条件列表
#                     "participant$p30903_i0": [
#                         {"condition": "between", "values": [0, 2]}
#                     ]
#                 }
#             }
#         ]
#     }
# })

In [7]:
dd[dd['entity'].str.contains('olink')]

,entity,name,type,primary_key_type,coding_name,concept,description,folder_path,is_multi_select,is_sparse_coding,linkout,longitudinal_axis_type,referenced_entity_field,relationship,title,units
32803,olink_instance_0,eid,string,local,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,participant:eid,one_to_one,Participant ID,NaN
32804,olink_instance_0,a1bg,float,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A1BG;Alpha-1B-glycoprotein,NaN
32805,olink_instance_0,aamdc,float,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AAMDC;Mth938 domain-containing protein,NaN
32806,olink_instance_0,aarsd1,float,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AARSD1;Alanyl-tRNA editing protein Aarsd1,NaN
32807,olink_instance_0,abca2,float,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ABCA2;ATP-binding cassette sub-family A member 2,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38650,olink_instance_3,xrcc4,float,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,XRCC4;DNA repair protein XRCC4,NaN
38651,olink_instance_3,yes1,float,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YES1;Tyrosine-protein kinase Yes,NaN
38652,olink_instance_3,ythdf3,float,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YTHDF3;YTH domain-containing family protein 3,NaN
38653,olink_instance_3,zbtb16,float,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZBTB16;Zinc finger and BTB domain-containing p...,NaN
38654,olink_instance_3,zbtb17,float,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZBTB17;Zinc finger and BTB domain-containing p...,NaN

In [8]:
# 下载完整的olink数据
# 存在的问题：直接将所有column放进来会导致最终得到的df为空，需要分为多块进行整合。然而UKB有提到eid在不同的application数据获取之间会变化，这种切分方法也存在着潜在问题。
# 关于这一点，我需要进行主动测试。eid的变动会造成cohort的合并错误，计划通过比对两次cohort的合并结果是否一致来进行验证
# 更新：正确的方法应该是回避直接的数据下载，最简单的方法是使用cli的extract_table (应该也有对应的API，目前先实现数据提取)，导出数据后通过启动Workstation进行分析（也许可以下载到本地）


olink_cohort_set = dd[dd['entity'].str.contains(r'olink_.*0')]
olink_fields = olink_cohort_set['entity'] + '$' + olink_cohort_set['name']

olink0_cohort = client.create_cohort('olink_cohort_1', entity_fields=olink_fields.tolist()[:10], filters={}, folder="/")

In [9]:
olink0_cohort

DXCohortInfo(id='record-J7J6bQjJj70yKGY90vYbb3G8', name='olink_cohort_1', project='project-J3Y7p9jJj70gKV8XKv2yxqv5', folder='/', state='', description='', created=0, modified=0, participant_count=0, entity_fields=['olink_instance_0$eid', 'olink_instance_0$a1bg', 'olink_instance_0$aamdc', 'olink_instance_0$aarsd1', 'olink_instance_0$abca2', 'olink_instance_0$abhd14b', 'olink_instance_0$abl1', 'olink_instance_0$abo', 'olink_instance_0$abraxas2', 'olink_instance_0$acaa1'])

In [10]:
client.get_cohort(olink0_cohort.id)

DXRecordInfo(id='record-J7J6bQjJj70yKGY90vYbb3G8', name='olink_cohort_1', project='project-J3Y7p9jJj70gKV8XKv2yxqv5', folder='/', created=1775921859000, modified=1775921859531, state='open', description='', properties={}, types=['DatabaseQuery', 'CohortBrowser'], details={'databases': ['database-J77JYVjJVpqqx189JkJb87qG', 'database-Fx7Fj58JjG8Yf6bKPX9Yzykf'], 'dataset': {'$dnanexus_link': 'record-J77PBFjJVpqqvFz65XvV0Kk6'}, 'description': '', 'filters': {}, 'schema': 'ds-ukbrap-ver20', 'sql': 'SELECT `participant_0001_1`.`eid` AS `eid` FROM `database_j77jyvjjvpqqx189jkjb87qg__app917657_20260402210224`.`participant_0001` AS `participant_0001_1`;', 'version': '3.0', 'fields': ['olink_instance_0$eid', 'olink_instance_0$a1bg', 'olink_instance_0$aamdc', 'olink_instance_0$aarsd1', 'olink_instance_0$abca2', 'olink_instance_0$abhd14b', 'olink_instance_0$abl1', 'olink_instance_0$abo', 'olink_instance_0$abraxas2', 'olink_instance_0$acaa1']}, class='record', sponsored=False, hidden=False, links=['record-J77PBFjJVpqqvFz65XvV0Kk6'], tags=[], createdBy={'user': 'user-jiehua_li'}, size=646)

In [11]:
from dx_client import VizRawDataPayload

In [ ]:
results = client.vizserver.preview_cohort(
      cohort_id= olink0_cohort.id,                                                                        
      project=client.current_project_id,                          
      entity_fields=["participant$eid", "olink_instance_0$abca2"],
      limit=100,
  )

In [14]:
results

[{'eid': '1003322', 'abca2': None},
 {'eid': '1058592', 'abca2': None},
 {'eid': '1084658', 'abca2': None},
 {'eid': '1118047', 'abca2': None},
 {'eid': '1205661', 'abca2': None},
 {'eid': '1275060', 'abca2': None},
 {'eid': '1277228', 'abca2': None},
 {'eid': '1304914', 'abca2': None},
 {'eid': '1326221', 'abca2': None},
 {'eid': '1347257', 'abca2': None},
 {'eid': '1358556', 'abca2': None},
 {'eid': '1374354', 'abca2': None},
 {'eid': '1398242', 'abca2': None},
 {'eid': '1477403', 'abca2': None},
 {'eid': '1494140', 'abca2': None},
 {'eid': '1517882', 'abca2': None},
 {'eid': '1518040', 'abca2': None},
 {'eid': '1540916', 'abca2': None},
 {'eid': '1541596', 'abca2': None},
 {'eid': '1580168', 'abca2': None},
 {'eid': '1588759', 'abca2': None},
 {'eid': '1662560', 'abca2': None},
 {'eid': '1742222', 'abca2': None},
 {'eid': '1747995', 'abca2': None},
 {'eid': '1758105', 'abca2': None},
 {'eid': '1793714', 'abca2': None},
 {'eid': '1890219', 'abca2': None},
 {'eid': '1912122', 'abca2': None},
 {'eid': '1976843', 'abca2': None},
 {'eid': '2013853', 'abca2': None},
 {'eid': '2019264', 'abca2': None},
 {'eid': '2052025', 'abca2': None},
 {'eid': '2064450', 'abca2': None},
 {'eid': '2068735', 'abca2': None},
 {'eid': '2084896', 'abca2': None},
 {'eid': '2099621', 'abca2': None},
 {'eid': '2114237', 'abca2': None},
 {'eid': '2114719', 'abca2': None},
 {'eid': '2116918', 'abca2': None},
 {'eid': '2137484', 'abca2': None},
 {'eid': '2199481', 'abca2': None},
 {'eid': '2205399', 'abca2': None},
 {'eid': '2216620', 'abca2': None},
 {'eid': '2245556', 'abca2': None},
 {'eid': '2277582', 'abca2': None},
 {'eid': '2322295', 'abca2': None},
 {'eid': '2329611', 'abca2': None},
 {'eid': '2374040', 'abca2': None},
 {'eid': '2449562', 'abca2': None},
 {'eid': '2606304', 'abca2': None},
 {'eid': '2656511', 'abca2': None},
 {'eid': '2680984', 'abca2': None},
 {'eid': '2686173', 'abca2': None},
 {'eid': '2697994', 'abca2': None},
 {'eid': '2755003', 'abca2': None},
 {'eid': '2759500', 'abca2': None},
 {'eid': '2780333', 'abca2': None},
 {'eid': '2800871', 'abca2': None},
 {'eid': '2824629', 'abca2': None},
 {'eid': '2850909', 'abca2': None},
 {'eid': '2864988', 'abca2': None},
 {'eid': '2928655', 'abca2': None},
 {'eid': '2936330', 'abca2': None},
 {'eid': '2958430', 'abca2': None},
 {'eid': '2986102', 'abca2': None},
 {'eid': '3073673', 'abca2': None},
 {'eid': '3101766', 'abca2': None},
 {'eid': '3142568', 'abca2': None},
 {'eid': '3151668', 'abca2': None},
 {'eid': '3184122', 'abca2': None},
 {'eid': '3198663', 'abca2': None},
 {'eid': '3234605', 'abca2': None},
 {'eid': '3265913', 'abca2': None},
 {'eid': '3305047', 'abca2': None},
 {'eid': '3322318', 'abca2': None},
 {'eid': '3330819', 'abca2': None},
 {'eid': '3371954', 'abca2': None},
 {'eid': '3373921', 'abca2': None},
 {'eid': '3442622', 'abca2': None},
 {'eid': '3510486', 'abca2': None},
 {'eid': '3560322', 'abca2': None},
 {'eid': '1157180', 'abca2': 0.06725},
 {'eid': '1246236', 'abca2': -0.2119},
 {'eid': '1247702', 'abca2': 0.59335},
 {'eid': '1310175', 'abca2': None},
 {'eid': '1348894', 'abca2': 0.1539},
 {'eid': '1390164', 'abca2': None},
 {'eid': '1498880', 'abca2': 0.18905},
 {'eid': '1638360', 'abca2': -0.19735},
 {'eid': '1733057', 'abca2': None},
 {'eid': '1848056', 'abca2': -0.2748},
 {'eid': '1910402', 'abca2': 0.04735},
 {'eid': '2784887', 'abca2': -0.3867},
 {'eid': '2829975', 'abca2': 0.2671},
 {'eid': '3044520', 'abca2': -0.545},
 {'eid': '3104043', 'abca2': 0.182},
 {'eid': '3142052', 'abca2': -0.36505},
 {'eid': '3350645', 'abca2': -0.21405},
 {'eid': '3378143', 'abca2': 0.1342},
 {'eid': '3385589', 'abca2': 0.00175}]